DROP DATABASE ex3;
CREATE DATABASE ex3;
USE ex3;

CREATE TABLE Director (
  DirectorID INTEGER NOT NULL,
  Name VARCHAR(32),
  CONSTRAINT DirectorPK PRIMARY KEY (DirectorID));

CREATE TABLE Movie (
  MovieID INTEGER NOT NULL,
  Title VARCHAR(32),
  ProductionYear INTEGER,
  DirectorID INTEGER NOT NULL,
  CONSTRAINT MoviePK PRIMARY KEY (MovieID),
  CONSTRAINT MovieDirectorFK FOREIGN KEY (DirectorID) REFERENCES Director(DirectorID));

CREATE TABLE Genre (
    GenreID INTEGER NOT NULL,
    Name VARCHAR(32),
    Description TEXT,
    CONSTRAINT GenrePK PRIMARY KEY (GenreID));

CREATE TABLE GenreInMovie (
  GenreID INTEGER NOT NULL,
  MovieID INTEGER NOT NULL,
  CONSTRAINT MovieGenreFK FOREIGN KEY (GenreID) REFERENCES Genre(GenreID),
  CONSTRAINT GenreMovieFK FOREIGN KEY (MovieID) REFERENCES Movie(MovieID)
    ON UPDATE CASCADE
    ON DELETE CASCADE);

CREATE TABLE Actor (
  ActorID INTEGER NOT NULL,
  Name VARCHAR(32),
  BirthYear INTEGER,
  CONSTRAINT ActorPK PRIMARY KEY (ActorID));

CREATE TABLE ActorInMovie (
  MovieID INTEGER NOT NULL,
  ActorID INTEGER NOT NULL,
  Role VARCHAR(32),
  CONSTRAINT MovieActorFK FOREIGN KEY (ActorID) REFERENCES Actor(ActorID),
  CONSTRAINT ActorMovieFK FOREIGN KEY (MovieID) REFERENCES Movie(MovieID)
    ON UPDATE CASCADE
    ON DELETE CASCADE);
